remote_theme: pages-themes/minimal@v0.2.0 
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata

github:
  username: jidec

nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "CV"
    url: "/cv"
  - title: "Publications"
    url: "/publications"
  - title: "Blog"
    url: "/blog"
  - title: "Contact"
    url: "/contact"
